title: AI Engineering
page-top-title: AI Engineering
top-section-bg-text: Данные для языковых моделей
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.55
copyright-text: '&copy; AI Engineering 2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/project-engineering-ai/ai-engineering.space
license-link:
  text: License
  href: https://github.com/project-engineering-ai/ai-engineering.space/blob/main/LICENSE
sections:
  - id: home
    nav: ГЛАВНАЯ
    title: О КОМАНДЕ
    href: '#page-top'
  - id: services
    nav: УСЛУГИ
    title: УСЛУГИ
    icon: bi-gear-fill
  - id: blog
    nav: БЛОГ
    title: БЛОГ
    icon: bi-journal-text
    href: '#blog'
  - id: contact
    nav: КОНТАКТЫ
    title: КОНТАКТЫ
    icon: bi-envelope-fill
